services:
  # lotof.template.redis:
  #   image: redis:latest
  #   container_name: lotof.template.redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - lotof-network

  lotof.template.postgres:
    image: postgres:latest
    container_name: lotof.template.postgres
    depends_on:
      - network.create
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dima3raza
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - lotof-network

volumes:
  pgdata:

networks:
  lotof-network:
    external: true