services:
  lotof.template.gateway:
    container_name: lotof.template.gateway
    image: ghcr.io/pieceowater-dev/lotof.template.gateway:5484c5a
    platform: linux/amd64
    ports:
      - "80:3000"

  lotof.template.service:
    container_name: lotof.template.service
    image: ghcr.io/pieceowater-dev/lotof.template.service:main
    platform: linux/amd64
    ports:
      - "81:3000"
  
