services:
  lotof.template.gateway:
    container_name: lotof.template.gateway
    image: ghcr.io/pieceowater-dev/lotof.template.gateway
    platform: linux/amd64
    # depends_on:
    #   lotof.template.rabbitmq:
    #     condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://guest:guest@lotof.template.rabbitmq:5672
    ports:
      - "80:3000"
    networks:
      - lotof-template-network

  lotof.template.service:
    container_name: lotof.template.service
    image: ghcr.io/pieceowater-dev/lotof.template.service:main
    platform: linux/amd64
    # depends_on:
    #   lotof.template.rabbitmq:
    #     condition: service_healthy
    #   lotof.template.postgres:
    #     condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://guest:guest@lotof.template.rabbitmq:5672
      - DATABASE_URL=postgres://postgres:dima3raza@lotof.template.postgres:5432/template
    ports:
      - "81:3000"
    networks:
      - lotof-template-network

networks:
  lotof-template-network:
    external: true
