networks:
  lotof-loki:
  lotof-template-network:
    external: true

services:
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3011:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - lotof-loki
      - lotof-template-network

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - lotof-loki
      - lotof-template-network

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_USER=pieceowater
      - GF_SECURITY_ADMIN_PASSWORD=dima3raza
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3010
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3010:3000"
    networks:
      - lotof-loki
      - lotof-template-network