services:
  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"
    networks:
      - tools-network

  postgres:
    image: postgres:latest
    container_name: postgres-db-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dima3raza
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tools-network

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    container_name: pgadmin-local
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5431:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ~/Downloads/pieceowater-qpay-serv.pem:/pieceowater-qpay-serv.pem
    depends_on:
      - postgres
    networks:
      - tools-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-local
    ports:
      - "15671:15671"
      - "15672:15672"
      - "15691:15691"
      - "15692:15692"
      - "25672:25672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
    networks:
      - tools-network

volumes:
  pgdata:
  pgadmin-data:

networks:
  tools-network:
