services:
  lotof.template.service:
    container_name: lotof.template.service
    image: ghcr.io/pieceowater-dev/lotof.template.service:main
    platform: linux/amd64
    environment:
      - RABBITMQ_URL=amqp://guest:guest@lotof.template.rabbitmq:5672
      - DATABASE_URL=postgres://postgres:dima3raza@lotof.template.postgres:5432/template
    ports:
      - "3001:3000"
    networks:
      - lotof-template-network

networks:
  lotof-template-network:
    external: true
