services:
  certbot:
    container_name: lotof.certbot
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email pieceowater@gmail.com --agree-tos --no-eff-email -d api.template.lotof.services -d template.lotof.services -d *.lotof.services
    networks:
      - lotof-template-network
    entrypoint: ["/bin/sh", "-c", "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"]

  nginx:
    container_name: lotof.nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    networks:
      - lotof-template-network
    depends_on:
      certbot:
        condition: service_completed_successfully

networks:
  lotof-template-network:
    external: true
