services:
  certbot:
    container_name: lotof.certbot
    build: .
    volumes:
      - ~/tools/nginx/certs:/etc/letsencrypt
      - ~/tools/nginx/certbot/www:/var/www/certbot
      - ~/.aws/credentials:/root/.aws/credentials:ro
    command: certonly --dns-route53 --email pieceowater@gmail.com --agree-tos --no-eff-email --non-interactive --quiet -d api.template.lotof.services -d '*.lotof.services'
    networks:
      - lotof-template-network

  renewal:
    container_name: lotof.certbot-renewal
    build: .
    volumes:
      - ~/tools/nginx/certs:/etc/letsencrypt
      - ~/tools/nginx/certbot/www:/var/www/certbot
      - ~/.aws/credentials:/root/.aws/credentials:ro
    entrypoint: /bin/sh
    command: -c "while true; do certbot renew --dns-route53 --quiet --non-interactive; sleep 12h; done;"
    networks:
      - lotof-template-network

  nginx:
    container_name: lotof.nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/tools/nginx:/etc/nginx
      - ~/tools/nginx/certs:/etc/letsencrypt:ro
      - ~/tools/nginx/certbot/www:/var/www/certbot
    networks:
      - lotof-template-network
    depends_on:
      certbot:
        condition: service_completed_successfully

networks:
  lotof-template-network:
    external: true