services:
  template.nginx:
    container_name: lotof.template.nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./template-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./template-certs:/etc/letsencrypt:ro
      - ./template-certbot/www:/var/www/certbot
    networks:
      - lotof-template-network

  template.certbot:
    image: certbot/certbot
    volumes:
      - ./template-certs:/etc/letsencrypt
      - ./template-certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  lotof-template-network:
    external: true
