services:
  template.certbot:
    image: certbot/certbot
    volumes:
      - ./template-certs:/etc/letsencrypt
      - ./template-certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email pieceowater@gmail.com --agree-tos --no-eff-email -d api.template.lotof.services
    networks:
      - lotof-template-network
    entrypoint: ["/bin/sh", "-c", "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"]

  template.nginx:
    container_name: lotof.template.nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./template-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./template-certs:/etc/letsencrypt:ro
      - ./template-certbot/www:/var/www/certbot
    networks:
      - lotof-template-network
    depends_on:
      template.certbot:
        condition: service_completed_successfully

networks:
  lotof-template-network:
    external: true
