services:
  lotof.template.gateway:
    container_name: lotof.template.gateway
    image: ghcr.io/pieceowater-dev/lotof.template.gateway:90c877d
    platform: linux/amd64
    environment:
      - RABBITMQ_URL=amqp://guest:guest@lotof.template.rabbitmq:5672
    ports:
      - "3000:3000"
    networks:
      - lotof-template-network

networks:
  lotof-template-network:
    external: true
