services:
  lotof.template.rabbitmq:
    image: rabbitmq:3.13-management
    container_name: lotof.template.rabbitmq
    depends_on:
      - network.create
    ports:
      - "15671:15671"
      - "15672:15672"
      - "15691:15691"
      - "15692:15692"
      - "25672:25672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
    networks:
      - lotof-network

networks:
  lotof-network:
    external: true