services:
  lotof.template.rabbitmq:
    image: rabbitmq:3.13-management
    container_name: lotof.template.rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "15671:15671"
      - "15672:15672"
      - "15691:15691"
      - "15692:15692"
      - "25672:25672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
    networks:
      - lotof-template-network

networks:
  lotof-template-network:
    external: true